const recipes = [
  {
    title: "AI Butter Paneer",
    image:
      "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=1200&auto=format&fit=crop",
    category: "Indian",
  },
  {
    title: "Healthy Pasta Bowl",
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?q=80&w=1200&auto=format&fit=crop",
    category: "Healthy",
  },
  {
    title: "Protein Power Salad",
    image:
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=1200&auto=format&fit=crop",
    category: "Fitness",
  },
  {
    title: "Spicy Veg Pizza",
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200&auto=format&fit=crop",
    category: "Fast Food",
  },
  {
    title: "Creamy Mushroom Pasta",
    image:
      "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?q=80&w=1200&auto=format&fit=crop",
    category: "Italian",
  },
  {
    title: "Chocolate AI Dessert",
    image:
      "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=1200&auto=format&fit=crop",
    category: "Dessert",
  },
];

const FeaturedRecipes = () => {
  return (
    <section className="relative bg-zinc-950 py-32 px-6 overflow-hidden">

      {/* Top Divider */}
      <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-orange-500 to-transparent"></div>

      {/* Glow Effects */}
      <div className="absolute top-20 left-10 w-72 h-72 bg-orange-500/10 blur-3xl rounded-full"></div>

      <div className="absolute bottom-10 right-10 w-72 h-72 bg-amber-500/10 blur-3xl rounded-full"></div>

      <div className="relative z-10 max-w-7xl mx-auto">

        {/* Heading */}
        <div className="text-center max-w-4xl mx-auto">

          <p className="inline-block px-5 py-2 rounded-full bg-orange-500/10 border border-orange-400/20 text-orange-300 text-sm font-semibold tracking-[2px]">
            FEATURED AI RECIPES
          </p>

          <h1 className="text-4xl md:text-6xl font-bold text-white mt-8">
            Explore AI-Generated
            <span className="text-orange-400"> Delicious Recipes</span>
          </h1>

          <p className="text-zinc-400 text-lg leading-relaxed mt-6">
            Discover trending recipes generated by KitchenGPT —
            personalized, creative, and made with AI-powered cooking intelligence.
          </p>

        </div>

        {/* Recipe Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-10 mt-24">

          {recipes.map((recipe, index) => (
            <div
              key={index}
              className="group relative bg-white/5 border border-white/10 backdrop-blur-xl rounded-[28px] overflow-hidden hover:border-orange-400/30 transition duration-300"
            >

              {/* Card Glow */}
              <div className="absolute -top-20 -right-20 w-56 h-56 bg-orange-500/10 blur-3xl rounded-full opacity-0 group-hover:opacity-100 transition duration-500"></div>

              {/* Image */}
              <div className="overflow-hidden">

                <img
                  src={recipe.image}
                  alt={recipe.title}
                  className="w-full h-64 object-cover group-hover:scale-110 transition duration-500"
                />

              </div>

              {/* Content */}
              <div className="relative z-10 p-6">

                <span className="inline-block px-4 py-2 rounded-full bg-orange-500/10 border border-orange-400/20 text-orange-300 text-xs font-semibold tracking-[1px]">
                  {recipe.category}
                </span>

                <h2 className="text-2xl font-bold text-white mt-5">
                  {recipe.title}
                </h2>

                <p className="text-zinc-400 mt-4 leading-relaxed">
                  AI-crafted recipe ideas with rich flavors,
                  smart ingredients, and perfect meal inspiration.
                </p>

                <button className="mt-8 w-full bg-orange-500 hover:bg-orange-400 transition duration-300 text-white py-4 rounded-2xl font-semibold shadow-lg shadow-orange-500/20">

                  View Recipe

                </button>

              </div>

            </div>
          ))}

        </div>

      </div>

    </section>
  );
};

export default FeaturedRecipes;